name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  ci:
    name: CI
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: npm ci

      - name: Run Typechecks
        run: npm run tsc

      # - name: Run Tests
      #   run: npm test

      - name: Build
        run: npm run build
